<?php
/**
 * 首页
 * @category WuxcBlog
 * @copyright Copyright (c) 2016 PhalconCMS team (http://www.wuxceng.cn)
 * @license GNU General Public License 2.0
 * @link www.wuxceng.cn
 */

namespace Wuxc\Apps\Backend\Controllers;

use Wuxc\Apps\Backend\Models\UsersModel;
use Wuxc\Apps\Backend\Repositories\RepositoryFactory;

class PassportController extends BaseController{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAction(){

        $this -> view -> setVars(
            [
                'title' => $this -> config -> application -> app_name,
                'assetsVersion' => strtotime(date('Y-m-d H', time()) . ":00:00"),
            ]
        );
        $this -> view -> setMainView('passport/login');
    }

    public function loginAction(){
        try{
            if($this -> request -> isAjax() || !$this -> request -> isPost()){
                throw new \Exception('非法请求');
            }
            $username = $this -> request -> getPost('username', 'trim');
            $password = $this -> request -> getPost('userpwd', 'trim');
            /** 添加验证规则 */

            /** 进行登录处理 */
            RepositoryFactory::get_repository('Users') -> login($username, $password);
            return $this -> response ->redirect('dashboard/index');
        }catch(\Exception $e){
            $this -> write_exception_log($e);
            $this -> flashSession -> error($e -> getMessage());
            $this -> response -> redirect('passport/index');
        }
    }
}