<?php
/**
 * 首页
 * @category WuxcBlog
 * @copyright Copyright (c) 2016 PhalconCMS team (http://www.wuxceng.cn)
 * @license GNU General Public License 2.0
 * @link www.wuxceng.cn
 */

namespace Wuxc\Apps\Backend\Controllers;

class PassportController extends BaseController{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAction(){

        $this -> view -> setVars(
            [
                'title' => $this -> config -> application -> app_name,
                'assetsVersion' => strtotime(date('Y-m-d H', time()) . ":00:00"),
            ]
        );
        $this -> view -> setMainView('passport/login');

    }

}